name: Build, Validate, Deploy and Publish
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build and validate spec, then deploy and publish (only if push to main branch)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
